apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - service.yaml

helmCharts:
  - name: librenms
    repo: https://www.librenms.org/helm-charts
    version: 7.2.0
    releaseName: librenms
    namespace: monitoring
    valuesFile: values.yaml
