apiVersion: v1
kind: ConfigMap
metadata:
  name: yamtrack-config
data:
  TZ: "Europe/Oslo"
  REDIS_URL: "redis://redis:6379"
  DB_HOST: "db" # This resolves to the service defined below
  DB_NAME: "yamtrack"
  DB_USER: "jochristian"
  DB_PORT: "5432"
  DB_SSL_MODE: "require"
  WEB_CONCURRENCY: "4"
  SOCIAL_PROVIDERS: 'allauth.socialaccount.providers.github'
  SOCIALACCOUNT_PROVIDERS: '{"github":{"SCOPE":["user","repo","read:org"]}}'
  ADMIN_ENABLED: 'True'
